# railway.toml ─ configurazione esplicita per Railpack
[build]
install  = "npm ci"
command  = "npm run build"

[start]
command            = "npm start"
healthcheck_path   = "/healthz"
healthcheck_timeout = 10

[variables]
NODE_ENV                      = "production"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
